---
builds:
- 
  main: ./cmd/koala/main.go
  env:
  - CGO_ENABLED=0

archive:
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
  format: tar.gz

checksum:
  name_template: '{{.ProjectName}}_checksums.txt'

changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
